micronaut:
  application:
    name: micronaut-camunda-example
camunda:
  #admin-user:
  #  id: admin
  #  password: admin
  generic-properties:
    properties:
      initialize-telemetry: true
  webapps:
    enabled: true
  rest:
    enabled: true
  filter:
    create: "All tasks"
